package yuuine.docmind.core.audit.valueobject;

public enum AuditAction {
    USER_REGISTER,
    USER_LOGIN,
    USER_UPDATE_PROFILE,
    DELETE_USER,
    DOCUMENT_UPLOAD,
    DOCUMENT_DOWNLOAD,
    DOCUMENT_DELETE,
    CHAT_SESSION_CREATE,
    CHAT_SESSION_UPDATE,
    CHAT_SESSION_DELETE,
    CHAT_MESSAGE_SEND,
    QUERY_AUDIT_LOG
}
